import { Platform, StyleSheet } from 'react-native';

export const fonts = {
  regular: 'Figtree_400Regular',
  medium: 'Figtree_500Medium',
  semibold: 'Figtree_600SemiBold',
};

export const colors = {
  primary: '#FFAF00',
  onPrimary: '#111111', // black text/icons on amber surfaces
  ink: '#111111', // primary text
  surface: '#ffffff',
  dark: '#111111', // large dark panels (status strip, cart bar)
};

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  buttonPressed: {
    backgroundColor: '#f3f3f3',
  },
  primaryActionPressed: {
    backgroundColor: '#2a2a2a',
  },
  dangerButtonPressed: {
    backgroundColor: '#fef2f2',
  },
  page: {
    padding: 24,
    gap: 24,
  },
  authPage: {
    flexGrow: 1,
    paddingTop: 32,
    paddingBottom: 40,
  },
  authLogoWrap: {
    alignItems: 'center',
    marginBottom: 4,
  },
  authCenter: {
    flex: 1,
    justifyContent: 'flex-start',
    gap: 24,
  },
  banner: {
    backgroundColor: '#f7f7f7',
    borderColor: '#d8d8d8',
    borderWidth: 1,
    borderRadius: 8,
    padding: 12,
    gap: 4,
  },
  bannerTitle: {
    color: '#111111',
    fontSize: 14,
    fontFamily: fonts.medium,
  },
  bannerText: {
    color: '#555555',
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 18,
  },
  authHeader: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    gap: 10,
  },
  brandLogo: {
    width: 210,
    height: 60, // preserves the logo's ~3.5:1 aspect ratio
    alignSelf: 'center',
  },
  authTitle: {
    color: '#111111',
    fontSize: 30,
    fontFamily: fonts.semibold,
    letterSpacing: 0,
    lineHeight: 36,
  },
  authSubtitle: {
    color: '#606060',
    fontSize: 15,
    fontFamily: fonts.regular,
    lineHeight: 22,
  },
  appHeader: {
    paddingTop: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  appHeaderCentered: {
    alignItems: 'center',
  },
  appHeaderText: {
    flex: 1,
    gap: 8,
  },
  appHeaderBackButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 4,
    paddingRight: 8,
  },
  appName: {
    color: '#111111',
    fontSize: 24,
    fontFamily: fonts.semibold,
    letterSpacing: 0,
    lineHeight: 30,
  },
  kicker: {
    color: '#777777',
    fontSize: 12,
    fontFamily: fonts.medium,
    letterSpacing: 0,
  },
  title: {
    color: '#111111',
    fontSize: 28,
    fontFamily: fonts.semibold,
    letterSpacing: 0,
    lineHeight: 34,
  },
  subtitle: {
    color: '#666666',
    fontSize: 15,
    fontFamily: fonts.regular,
    lineHeight: 22,
  },
  tabBar: {
    flexDirection: 'row',
    gap: 8,
  },
  tabButton: {
    flex: 1,
    minHeight: 46,
    borderWidth: 1,
    borderColor: '#d8d8d8',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 11,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 6,
    backgroundColor: '#ffffff',
  },
  tabButtonActive: {
    backgroundColor: colors.dark,
    borderColor: colors.dark,
  },
  tabButtonActivePressed: {
    backgroundColor: '#2a2a2a',
  },
  tabButtonText: {
    color: '#111111',
    fontSize: 13,
    fontFamily: fonts.medium,
  },
  tabButtonTextActive: {
    color: colors.primary,
  },
  backButton: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingVertical: 6,
    paddingRight: 8,
  },
  backButtonText: {
    color: '#111111',
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  utilityText: {
    color: '#111111',
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  iconOnlyButton: {
    width: 42,
    height: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d8d8d8',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  workspace: {
    gap: 12,
  },
  authForm: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    gap: 12,
  },
  workspaceHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingTop: 4,
  },
  workspaceTitle: {
    color: '#111111',
    fontSize: 18,
    fontFamily: fonts.semibold,
  },
  rowButton: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    gap: 12,
  },
  rowButtonPressed: {
    backgroundColor: '#f3f3f3',
  },
  rowButtonTextBlock: {
    flex: 1,
    minWidth: 0,
  },
  rowChevron: {
    width: 22,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  rowAddButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 36,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#111111',
    backgroundColor: '#ffffff',
  },
  rowAddButtonText: {
    color: '#111111',
    fontSize: 13,
    fontFamily: fonts.medium,
  },
  warningRow: {
    borderColor: '#f59e0b',
    backgroundColor: '#fff7ed',
  },
  warningRowPressed: {
    backgroundColor: '#ffedd5',
  },
  warningTitle: {
    color: '#9a3412',
  },
  warningDetail: {
    color: '#c2410c',
  },
  rowTitle: {
    color: '#111111',
    fontSize: 15,
    fontFamily: fonts.medium,
  },
  rowDetail: {
    color: '#666666',
    fontSize: 13,
    fontFamily: fonts.regular,
    marginTop: 4,
  },
  fieldLabel: {
    color: '#555555',
    fontSize: 12,
    fontFamily: fonts.medium,
  },
  requiredAsterisk: {
    color: '#b42318',
  },
  input: {
    borderWidth: 1,
    borderColor: '#d8d8d8',
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    minHeight: 54,
    backgroundColor: '#ffffff',
    color: '#111111',
    fontSize: 16,
    fontFamily: fonts.regular,
  },
  readOnlyInput: {
    backgroundColor: '#f6f6f6',
    borderColor: '#e0e0e0',
  },
  datePickerButton: {
    borderWidth: 1,
    borderColor: '#d8d8d8',
    borderRadius: 8,
    paddingHorizontal: 14,
    minHeight: 54,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
  },
  datePickerText: {
    color: '#111111',
    fontSize: 16,
    fontFamily: fonts.regular,
  },
  datePickerFrame: {
    minHeight: Platform.OS === 'ios' ? 216 : 0,
    justifyContent: 'center',
  },
  nativeDatePicker: {
    width: '100%',
    height: Platform.OS === 'ios' ? 216 : undefined,
  },
  placeholderText: {
    color: '#9a9a9a',
  },
  compactInput: {
    fontSize: 14,
    paddingVertical: 9,
  },
  searchPanel: {
    gap: 8,
  },
  draftCartSection: {
    gap: 8,
    paddingBottom: 8,
  },
  openCartsWidget: {
    backgroundColor: '#ffffff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d8d8d8',
    overflow: 'hidden',
  },
  openCartsHeader: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  chevronExpanded: {
    transform: [{ rotate: '90deg' }],
  },
  draftCartRow: {
    backgroundColor: '#ffffff',
    borderTopWidth: 1,
    borderTopColor: '#eeeeee',
  },
  draftCartOpen: {
    padding: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  draftCartClear: {
    minHeight: 42,
    borderTopWidth: 1,
    borderTopColor: '#eeeeee',
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  draftCartClearText: {
    color: '#b42318',
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  groupFilterHeader: {
    gap: 8,
  },
  groupChips: {
    gap: 8,
    paddingRight: 24,
  },
  groupChip: {
    borderWidth: 1,
    borderColor: '#d8d8d8',
    borderRadius: 8,
    paddingHorizontal: 13,
    paddingVertical: 9,
    backgroundColor: '#ffffff',
  },
  groupChipActive: {
    borderColor: colors.dark,
    backgroundColor: colors.dark,
  },
  groupChipActivePressed: {
    backgroundColor: '#2a2a2a',
  },
  groupChipText: {
    color: '#555555',
    fontSize: 13,
    fontFamily: fonts.regular,
  },
  groupChipTextActive: {
    color: colors.primary,
  },
  itemRow: {
    borderWidth: 1,
    borderColor: '#e0e0e0',
    borderRadius: 8,
    padding: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    backgroundColor: '#ffffff',
  },
  itemRowText: {
    flex: 1,
  },
  itemAddPill: {
    minWidth: 64,
    minHeight: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.ink,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  itemAddPillActive: {
    backgroundColor: colors.dark,
    borderColor: colors.dark,
  },
  itemAddPillText: {
    color: '#111111',
    fontSize: 13,
    fontFamily: fonts.medium,
  },
  itemAddPillTextActive: {
    color: colors.primary,
  },
  helperText: {
    color: '#666666',
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 19,
  },
  loadingProducts: {
    minHeight: 120,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  cartHint: {
    color: '#777777',
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 19,
  },
  summaryLine: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  summaryItemText: {
    flex: 1,
    minWidth: 0,
    paddingTop: 2,
  },
  summaryItemTitle: {
    lineHeight: 20,
    flexWrap: 'wrap',
  },
  contextBlock: {
    gap: 10,
    paddingBottom: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
  },
  quantity: {
    color: '#111111',
    fontSize: 16,
    fontFamily: fonts.medium,
    minWidth: 28,
    textAlign: 'center',
  },
  cartControls: {
    width: 154,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    gap: 6,
  },
  iconButton: {
    width: 34,
    height: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d8d8d8',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffffff',
  },
  iconButtonPressed: {
    backgroundColor: '#f3f3f3',
  },
  note: {
    color: '#444444',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    padding: 12,
    fontSize: 13,
    fontFamily: fonts.regular,
    lineHeight: 18,
  },
  primaryAction: {
    backgroundColor: colors.dark,
    borderRadius: 8,
    padding: 15,
    minHeight: 54,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    marginTop: 4,
  },
  authPrimaryAction: {
    marginTop: 18,
  },
  authInlinePrimaryAction: {
    flex: 1,
    marginTop: 0,
  },
  authSplitActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 18,
  },
  authSecondaryAction: {
    flex: 1,
    minHeight: 54,
  },
  secondaryAction: {
    flex: 1,
    minHeight: 56,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#d8d8d8',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 13,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  secondaryActionText: {
    color: '#111111',
    fontSize: 14,
    fontFamily: fonts.regular,
    textAlign: 'center',
    flexShrink: 1,
  },
  actionRow: {
    flexDirection: 'row',
    gap: 10,
  },
  primaryActionText: {
    color: colors.primary,
    fontSize: 15,
    fontFamily: fonts.medium,
  },
  textAction: {
    paddingVertical: 8,
    alignItems: 'center',
  },
  authTextAction: {
    paddingVertical: 10,
    marginTop: 12,
    alignItems: 'center',
  },
  textActionText: {
    color: '#111111',
    fontSize: 15,
    fontFamily: fonts.regular,
    textDecorationLine: 'underline',
  },
  successRef: {
    color: '#111111',
    fontSize: 28,
    fontFamily: fonts.semibold,
  },
  cartBar: {
    margin: 14,
    marginTop: 0,
    borderRadius: 8,
    backgroundColor: '#111111',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  cartBarTitle: {
    color: colors.primary,
    fontSize: 15,
    fontFamily: fonts.medium,
  },
  cartBarText: {
    color: '#c8c8c8',
    fontSize: 12,
    fontFamily: fonts.regular,
    marginTop: 2,
  },
  cartBarAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  cartBarActionText: {
    color: '#ffffff',
    fontSize: 14,
    fontFamily: fonts.regular,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  modalScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0, 0, 0, 0.28)',
  },
  bottomSheet: {
    maxHeight: '88%',
    backgroundColor: '#ffffff',
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    overflow: 'hidden',
  },
  bottomSheetContent: {
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 28,
    gap: 12,
  },
  sheetHandle: {
    alignSelf: 'center',
    width: 42,
    height: 4,
    borderRadius: 999,
    backgroundColor: '#d8d8d8',
    marginBottom: 8,
  },
  sheetHeader: {
    gap: 4,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eeeeee',
  },
  sheetSectionHeading: {
    gap: 4,
    marginTop: 4,
  },
  sheetFooterSpace: {
    height: 16,
  },
});
